server:
  port: 6066
  servlet:
    context-path: /demo

spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 15
      maximum-pool-size: 30
      auto-commit: true
      idle-timeout: 30000
      pool-name: HikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1

  redis:
    host: 172.22.27.136
    port: 6379
    database: 0
    password: 123456
    timeout: 2000

mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml

logging:
  config: classpath:log4j2.xml

---
#dev
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://10.179.38.6:3306/demo?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 123456
logging:
  level.com.enterprise: debug

---
#test
spring:
  profiles: test
  datasource:
    url: jdbc:mysql://10.179.38.6:3306/demo?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 123456
logging:
  level.com.enterprise: info

---
#prod
spring:
  profiles: prod
  datasource:
    url:
    username:
    password:
logging:
  level.com.enterprise: info


