server:
  port: 8090
spring:
  application:
    name: sys
  profiles:
    active: dev
  datasource:
    druid:
      # 初始化大小，最小，最大
      initial-size: 1
      min-idle: 3
      max-active: 20
      # 获取连接等待超时的时间
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 30000
      validation-query: select 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      # 打开PSCache，并且指定每个连接上PSCache的大小，Oracle设置为true，mysql可以设置为false
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: false
        wall:
          config:
            multi-statement-allow: true
        slf4j:
          enabled: true
      stat-view-servlet:
        url-pattern: /druid/*
        reset-enable: false
        login-username:
        login-password:

  redis:
    host: 172.16.107.128
    port: 6379
    database: 0
    password: 123456
    timeout: 2000

  thymeleaf:
    mode: LEGACYHTML5

mybatis-plus:
  mapper-locations: classpath:mapper/*Mapper.xml
  typeAliasesPackage: com.enterprise.demo.sys.entity
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID"
    id-type: 0
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 1
    db-column-underline: true
    #刷新mapper 调试神器
    #refresh-mapper: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false

logging:
  path: /Users/didi/logs/${spring.application.name}/
  file: ${spring.application.name}.log

#dubbo:
#  application:
#    name: demo-sys
#  protocol:
#    name: dubbo
#    port:  20880
#  registry:
#   address: zookeeper://192.168.196.128:2181?backup=192.168.196.128:2182,192.168.196.128:2183

---
#dev
spring:
  profiles: dev
  datasource:
    druid:
      url: jdbc:mysql://172.16.107.128:3306/sys?useUnicode=true&characterEncoding=utf8
      username: root
      password: 123456
logging:
  level.com.enterprise: debug

---
#test
spring:
  profiles: test
  datasource:
    druid:
      url:
      username:
      password:
logging:
  level.com.enterprise: info

---
#prod
spring:
  profiles: prod
  datasource:
    druid:
      url:
      username:
      password:
logging:
  level.com.enterprise: info


